import { parse, parseSetCookie } from 'cookie'
import { parsePageMetadata } from '../2-rewrite-origin-response/parsePageMetadata'
import type { SurfaceDecisionResponse } from '../types'
import fetchSurfaceDecisions from './fetchSurfaceDecisions'

export default async function getSurfaceDecisions(
    request: Request,
    env: Env,
    response: Response,
): Promise<[Response, SurfaceDecisionResponse | null]> {
    const { anonymousIdentifier, userJwt } = getExistingCookies(request, response, env)

    // Read origin metadata
    const [metadataStream, passThroughStream] = response.body?.tee() ?? [null, null]
    const pageMetadata = metadataStream ? await parsePageMetadata(new Response(metadataStream, response)) : {}
    let modifiedResponse = passThroughStream ? new Response(passThroughStream, response) : response

    // Make surface decision
    const surfaceDecisions = await fetchSurfaceDecisions({
        surfaceSlug: env.SURFACE_SLUG,
        anonymousIdentifier,
        userJwt,
        path: new URL(request.url).pathname,
        url: request.url,
        cf: request.cf,
        pageMetadata,
        userAgent: request.headers.get('User-Agent') ?? undefined,
        originStatus: response.status,
    })

    // Set anon cookie if required and generated by MOS
    if (!anonymousIdentifier && !userJwt && surfaceDecisions?.identity?.identifier) {
        const headers = new Headers(modifiedResponse.headers)
        headers.append('Set-Cookie', `${env.ANONYMOUS_SESSION_COOKIE_NAME}=${surfaceDecisions.identity.identifier}; Path=/`)
        modifiedResponse = new Response(modifiedResponse.body, {
            status: modifiedResponse.status,
            statusText: modifiedResponse.statusText,
            headers,
        })
    }

    return [modifiedResponse, surfaceDecisions]
}

const getExistingCookies = (request: Request, originResponse: Response, env: Env) => {
    // Origin headers
    const setCookies = originResponse.headers.getSetCookie().map((header) => parseSetCookie(header))
    const originAnonymousCookie = setCookies.find((s) => s.name === env.ANONYMOUS_SESSION_COOKIE_NAME)
    const originUserJwtCookie = setCookies.find((s) => s.name === env.AUTHENTICATED_USER_JWT_COOKIE_NAME)
    if (originAnonymousCookie || originUserJwtCookie) {
        return { anonymousIdentifier: originAnonymousCookie?.value, userJwt: originUserJwtCookie?.value }
    }

    // Request headers
    const cookies = parse(request.headers.get('Cookie') || '')
    const anonymousIdentifier = cookies[env.ANONYMOUS_SESSION_COOKIE_NAME]
    const userJwt = cookies[env.AUTHENTICATED_USER_JWT_COOKIE_NAME]
    return { anonymousIdentifier, userJwt }
}
